version: '3.7'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: front


    ports:
        - 3000:3000
    command: npm start
    volumes:
      - ./front/src:/usr/app/src
    tty: true
    stdin_open: true


  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: back

    ports:
        - 8000:8000
    command: npm run start
    volumes:
        - ./back/src:/usr/app/src





