version: '3.7'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    command: npm start
    volumes:
      - ./front/src:/usr/app/src
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_PORT=8080


  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
        - 8000:8000
    command: npm run start
    volumes:
        - ./back/src:/usr/app/src

  nignx:
     image: nginx:stable-alpine
     ports:
       - '8080:80'
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
     depends_on:
        - frontend
        - api



